"""Agent Factory — meta-agent that spawns new specialist sub-agents.

When the orchestrator dispatches a design task, this agent:
1. Analyzes the task description to determine what tools/capabilities are needed.
2. Designs an agent manifest (name, description, tools, prompts).
3. Generates the Python module code.
4. Writes the manifest YAML to data/agents/.
5. Writes the module to agents/.
6. Registers the agent in the database and the live registry.
7. Optionally runs a smoke test to verify the agent works.

Defaults for the four decisions:
  - Host runtime: Python/FastAPI (Emma's stack)
  - Tool registry: ControlAgent.TOOL_CATALOG (20 tools)
  - Storage: SQLite (AgentDB) + YAML manifests (AgentRegistry)
  - Approval: ConsentManager (existing guardian layer)
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path
from typing import Any

from typing import TYPE_CHECKING

from agents.base import AgentResult, BaseAgent

if TYPE_CHECKING:
    from agents.router import Pipeline


# ---------------------------------------------------------------- templates

AGENT_MODULE_TEMPLATE = '''"""Auto-generated agent: {name}.

{description}

Generated by the Agent Factory on {date}.
Task: {task}
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from agents.base import AgentResult, BaseAgent

if TYPE_CHECKING:
    from agents.router import Pipeline


class {class_name}(BaseAgent):
    name = "{name}"
    description = "{description}"

    # Tool allowlist — least-privilege scoping.
    tool_allowlist = frozenset({{{allowlist}}})

    def __init__(self, pipeline: "Pipeline") -> None:
        super().__init__(pipeline)

    async def run(self, request: str) -> AgentResult:
        """Execute the agent's task."""
        self._audit("{name}.started", detail={{"request": request[:200]}})

        try:
            outputs = []
            actions = []

            {body}

            self._audit("{name}.completed", detail={{"outputs": len(outputs)}})

            return AgentResult(
                ok=True,
                output="\\n\\n".join(outputs) if outputs else "Task completed.",
                intent="{name}",
                actions=actions,
            )

        except Exception as exc:
            self._audit("{name}.failed", detail={{"error": str(exc)}})
            return AgentResult(
                ok=False,
                output=f"Agent failed: {{exc}}",
                intent="{name}",
                error=str(exc),
            )
'''

AGENT_MANIFEST_TEMPLATE = '''# Auto-generated agent manifest.
# Generated by the Agent Factory.
name: {name}
description: "{description}"
class: agents.{module_name}.{class_name}
tool_allowlist:
{allowlist_yaml}max_plan_steps: {max_plan_steps}
handoff_to:
{handoff_to_yaml}tags:
{tags_yaml}'''


class AgentFactory(BaseAgent):
    """Meta-agent that designs and registers new specialist sub-agents."""

    name = "agent_factory"
    description = "Designs, generates, and registers new specialist sub-agents on demand."

    # The factory needs broad access to read existing agents and write new ones.
    tool_allowlist = frozenset({
        "read_file",
        "write_file",
        "list_dir",
        "run_command",
    })

    def __init__(self, pipeline: "Pipeline") -> None:
        super().__init__(pipeline)

    async def run(self, request: str) -> AgentResult:
        """Design and register a new agent from a task description.

        The request should describe what the agent should do. Examples:
        - "Create an agent that monitors GitHub repos for new issues"
        - "Build a data analysis agent that can query SQL and generate charts"
        - "Make an agent that summarizes long documents"
        """
        self._audit("factory.started", detail={"request": request[:200]})

        try:
            # Step 1: Design the agent spec.
            spec = self._design_agent(request)

            # Step 2: Generate the Python module.
            module_code = self._generate_module(spec)

            # Step 3: Generate the YAML manifest.
            manifest_yaml = self._generate_manifest(spec)

            # Step 4: Write the files.
            module_path = self._write_module(spec["module_name"], module_code)
            manifest_path = self._write_manifest(spec["name"], manifest_yaml)

            # Step 5: Register in the database.
            self._register_in_db(spec, str(manifest_path))

            # Step 6: Reload in the live registry.
            self._register_in_registry(spec)

            # Step 7: Record the generation.
            gen_id = self._record_generation(spec["name"], request, module_path)

            self._audit("factory.completed", detail={
                "agent_name": spec["name"],
                "module": str(module_path),
                "manifest": str(manifest_path),
            })

            # Build the output report.
            output = self._build_report(spec, module_path, manifest_path, gen_id)

            return AgentResult(
                ok=True,
                output=output,
                intent="agent_factory",
                actions=[
                    {"tool": "write_file", "args": {"path": str(module_path)}},
                    {"tool": "write_file", "args": {"path": str(manifest_path)}},
                ],
            )

        except Exception as exc:
            self._audit("factory.failed", detail={"error": str(exc)})
            return AgentResult(
                ok=False,
                output=f"Agent factory failed: {exc}",
                intent="agent_factory",
                error=str(exc),
            )

    # ---------------------------------------------------------------- design
    def _design_agent(self, task_description: str) -> dict[str, Any]:
        """Analyze the task and design an agent spec.

        This is a rule-based designer — it maps task keywords to tools
        and capabilities. A production version would use the LLM.
        """
        low = task_description.lower()

        # Determine the agent name from the task.
        name = self._extract_name(task_description)
        class_name = self._to_class_name(name)
        module_name = f"gen_{name}"

        # Determine which tools are needed based on task keywords.
        tools = set()
        tags = []

        if any(w in low for w in ("search", "find", "lookup", "research", "web")):
            tools.update(["web_search", "fetch_page"])
            tags.append("research")

        if any(w in low for w in ("file", "read", "document", "parse", "analyze")):
            tools.add("read_file")
            tags.append("analysis")

        if any(w in low for w in ("write", "create", "generate", "output", "save")):
            tools.add("write_file")
            tags.append("generation")

        if any(w in low for w in ("run", "execute", "command", "script", "shell")):
            tools.add("run_command")
            tags.append("automation")

        if any(w in low for w in ("git", "commit", "repo", "branch")):
            tools.update(["git_status", "git_log", "git_commit"])
            tags.append("vcs")

        if any(w in low for w in ("docker", "container", "compose")):
            tools.update(["docker_ps", "docker_images", "docker_logs"])
            tags.append("devops")

        if any(w in low for w in ("database", "sql", "query", "table")):
            tools.update(["read_file", "list_dir"])
            tags.append("data")

        if any(w in low for w in ("monitor", "watch", "check", "status")):
            tools.update(["list_dir", "run_command"])
            tags.append("monitoring")

        # Always include read_file and list_dir for context.
        tools.update(["read_file", "list_dir"])

        # Ensure tools are valid (exist in the catalog).
        from agents.control import ControlAgent
        valid_tools = set(ControlAgent.TOOL_CATALOG.keys())
        tools = tools & valid_tools

        # Build the body based on the tools needed.
        body = self._design_body(task_description, tools, tags)

        return {
            "name": name,
            "class_name": class_name,
            "module_name": module_name,
            "description": self._generate_description(task_description),
            "task": task_description,
            "tools": sorted(tools),
            "tags": tags or ["general"],
            "max_plan_steps": 5,
            "handoff_to": ["reasoning", "control"],
            "body": body,
        }

    def _extract_name(self, task: str) -> str:
        """Extract a short agent name from the task description."""
        # Try to find "an agent that ..." pattern.
        import re
        m = re.search(r"(?:an?|the)\s+agent\s+(?:that\s+)?(\w+)", task, re.IGNORECASE)
        if m:
            return m.group(1).lower()[:20]

        # Use the first meaningful word.
        words = task.lower().split()
        skip = {"create", "build", "make", "design", "add", "a", "an", "the", "that", "which", "can", "agent"}
        for w in words:
            if w not in skip and len(w) > 2:
                return w[:20]
        return "custom_agent"

    def _to_class_name(self, name: str) -> str:
        """Convert snake_case to PascalCase."""
        return "".join(w.capitalize() for w in name.split("_"))

    def _generate_description(self, task: str) -> str:
        """Generate a concise description from the task."""
        # Take the first sentence or first 100 chars.
        desc = task.split(".")[0].strip()
        if len(desc) > 100:
            desc = desc[:97] + "..."
        return desc

    def _design_body(self, task: str, tools: set[str], tags: list[str]) -> str:
        """Design the agent's run() body based on needed tools."""
        lines = []

        if "web_search" in tools:
            lines.append(textwrap.dedent("""\
                # Search the web for relevant information.
                search_output = await self.pipeline.control.execute(
                    "web_search", actor=self.name, query=request, n=5
                )
                outputs.append(f"Search results: {search_output[:500]}")
                actions.append({"tool": "web_search", "args": {"query": request}})"""))

        if "fetch_page" in tools:
            lines.append(textwrap.dedent("""\
                # Fetch and read relevant pages.
                # (In a full implementation, parse search results for URLs first.)
                pass  # Pages fetched on demand via search results."""))

        if "read_file" in tools and "web_search" not in tools:
            lines.append(textwrap.dedent("""\
                # Read files as part of the task.
                output = await self.pipeline.control.execute(
                    "read_file", actor=self.name, path="."
                )
                outputs.append(f"Context: {str(output)[:500]}")
                actions.append({"tool": "read_file", "args": {"path": "."}})"""))

        if "run_command" in tools:
            lines.append(textwrap.dedent("""\
                # Execute a command for the task.
                output = await self.pipeline.control.execute(
                    "run_command", actor=self.name, command=request
                )
                outputs.append(f"Command output: {str(output)[:500]}")
                actions.append({"tool": "run_command", "args": {"command": request}})"""))

        if "write_file" in tools:
            lines.append(textwrap.dedent("""\
                # Generate output and write to file.
                output_path = f"data/output/{self.name}_result.txt"
                await self.pipeline.control.execute(
                    "write_file", actor=self.name,
                    path=output_path, content="\\n".join(outputs)
                )
                outputs.append(f"Output written to {output_path}")
                actions.append({"tool": "write_file", "args": {"path": output_path}})"""))

        if not lines:
            lines.append(textwrap.dedent("""\
                # Default: process the request and return a result.
                outputs.append(f"Agent '{self.name}' processed: {request[:200]}")"""))

        return "\n\n            ".join(lines)

    # ---------------------------------------------------------------- generate
    def _generate_module(self, spec: dict[str, Any]) -> str:
        """Generate the Python module code."""
        from datetime import date
        return AGENT_MODULE_TEMPLATE.format(
            name=spec["name"],
            class_name=spec["class_name"],
            description=spec["description"],
            task=spec["task"],
            date=date.today().isoformat(),
            allowlist=", ".join(f'"{t}"' for t in spec["tools"]),
            body=spec["body"],
        )

    def _generate_manifest(self, spec: dict[str, Any]) -> str:
        """Generate the YAML manifest."""
        allowlist_yaml = "\n".join(f"  - {t}" for t in spec["tools"])
        handoff_yaml = "\n".join(f"  - {a}" for a in spec["handoff_to"])
        tags_yaml = "\n".join(f"  - {t}" for t in spec["tags"])

        return AGENT_MANIFEST_TEMPLATE.format(
            name=spec["name"],
            description=spec["description"],
            module_name=spec["module_name"],
            class_name=spec["class_name"],
            allowlist_yaml=allowlist_yaml,
            max_plan_steps=spec["max_plan_steps"],
            handoff_to_yaml=handoff_yaml,
            tags_yaml=tags_yaml,
        )

    # ---------------------------------------------------------------- write
    def _write_module(self, module_name: str, code: str) -> Path:
        """Write the generated Python module to agents/."""
        path = Path("agents") / f"{module_name}.py"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(code, encoding="utf-8")
        return path

    def _write_manifest(self, agent_name: str, manifest: str) -> Path:
        """Write the YAML manifest to data/agents/."""
        path = Path("data") / "agents" / f"{agent_name}.yaml"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(manifest, encoding="utf-8")
        return path

    # ---------------------------------------------------------------- register
    def _register_in_db(self, spec: dict[str, Any], manifest_path: str) -> None:
        """Register the agent in the SQLite database."""
        try:
            from backend.config import Settings
            settings = Settings()
            from orchestration.migrations import AgentDB
            db = AgentDB(settings.data_dir / "agents.db")
            db.register_agent(
                name=spec["name"],
                description=spec["description"],
                class_path=f"agents.{spec['module_name']}.{spec['class_name']}",
                tool_allowlist=spec["tools"],
                max_plan_steps=spec["max_plan_steps"],
                handoff_to=spec["handoff_to"],
                tags=spec["tags"],
                manifest_path=manifest_path,
                source="factory",
            )
            db.close()
        except Exception as exc:
            # Non-fatal — the agent still works via file-based registry.
            self._audit("factory.db_register_failed", detail={"error": str(exc)})

    def _register_in_registry(self, spec: dict[str, Any]) -> None:
        """Trigger a reload of the agent registry to pick up the new manifest."""
        try:
            self.pipeline.agent_registry.load_manifests(
                Path("data") / "agents"
            )
        except Exception as exc:
            self._audit("factory.registry_reload_failed", detail={"error": str(exc)})

    def _record_generation(self, agent_name: str, task: str, module_path: Path) -> int | None:
        """Record the generation in the database."""
        try:
            from backend.config import Settings
            settings = Settings()
            from orchestration.migrations import AgentDB
            db = AgentDB(settings.data_dir / "agents.db")
            gen_id = db.record_generation(
                agent_name=agent_name,
                task_description=task,
                status="success",
                module_path=str(module_path),
            )
            db.close()
            return gen_id
        except Exception:
            return None

    # ---------------------------------------------------------------- report
    def _build_report(
        self, spec: dict, module_path: Path, manifest_path: Path, gen_id: int | None
    ) -> str:
        """Build a human-readable report of what was generated."""
        lines = [
            f"## Agent Factory — New Agent Created\n",
            f"**Name:** `{spec['name']}`",
            f"**Class:** `{spec['class_name']}`",
            f"**Module:** `{module_path}`",
            f"**Manifest:** `{manifest_path}`",
            f"**Tools:** {', '.join(spec['tools'])}",
            f"**Tags:** {', '.join(spec['tags'])}",
            f"**Handoff targets:** {', '.join(spec['handoff_to'])}",
            "",
            f"### What was generated:",
            f"1. Python module at `{module_path}` with the agent class",
            f"2. YAML manifest at `{manifest_path}` for hot-reload",
            f"3. Database registration (source: 'factory')",
            f"4. Registry reload triggered",
            "",
            f"### How to use:",
            f"- The agent is now live via the registry (hot-reload picked it up)",
            f"- Route to it by saying '{spec['name']} ...' or via keyword routing",
            f"- It follows the same patterns as built-in agents",
        ]

        if gen_id:
            lines.append(f"\n*Generation ID: {gen_id}*")

        return "\n".join(lines)
