"""Auto-generated agent: code_reviewer.

create a code reviewer agent and use qwen3

Generated by the Agent Factory on 2026-08-12.
Task: create a code reviewer agent and use qwen3.5:2b for it
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from agents.base import AgentResult, BaseAgent
from security.guardian import ConsentRequiredError

if TYPE_CHECKING:
    from agents.router import Pipeline


class CodeReviewer(BaseAgent):
    name = "code_reviewer"
    description = "create a code reviewer agent and use qwen3"

    # Assigned Ollama model — this agent's LLM calls use it directly
    # (None = the normal router path: cloud gemma4 primary / local fallback).
    ollama_model = 'qwen3.5:2b'

    # Tool allowlist — least-privilege scoping.
    tool_allowlist = frozenset({"list_dir", "read_file", "write_file"})

    def __init__(self, pipeline: "Pipeline") -> None:
        super().__init__(pipeline)

    async def run(self, request: str) -> AgentResult:
        """Execute the agent's task."""
        self._audit("code_reviewer.started", detail={"request": request[:200]})

        try:
            outputs = []
            actions = []

                        # Gather context about the working directory.
            output = await self.pipeline.control.execute(
                "list_dir", actor=self.name, path="."
            )
            outputs.append(f"Directory context: {str(output)[:500]}")
            actions.append({"tool": "list_dir", "args": {"path": "."}})

            # Generate output and write to file.
            output_path = f"data/output/{self.name}_result.txt"
            await self.pipeline.control.execute(
                "write_file", actor=self.name,
                path=output_path, content="\n".join(outputs)
            )
            outputs.append(f"Output written to {output_path}")
            actions.append({"tool": "write_file", "args": {"path": output_path}})

            # Synthesize the final answer with THIS agent's own Ollama model
            # (assigned at creation; falls back to the normal LLM path when
            # the model is unavailable or unset).  A model hiccup never fails
            # the turn — gathered outputs are still returned.
            try:
                answer = await self.pipeline.llm.complete(
                    [
                        {"role": "system", "content": "You are code_reviewer, a specialist agent. create a code reviewer agent and use qwen3"},
                        {"role": "user", "content": "Task: " + request + "\n\nFindings:\n" + ("\n\n".join(outputs) if outputs else "(none)")},
                    ],
                    temperature=0.6,
                    max_tokens=600,
                    model=self.ollama_model or None,
                )
                outputs.append(answer)
            except Exception:
                pass  # keep going with whatever the tools gathered

            self._audit("code_reviewer.completed", detail={"outputs": len(outputs)})

            return AgentResult(
                ok=True,
                output="\n\n".join(outputs) if outputs else "Task completed.",
                intent="code_reviewer",
                actions=actions,
            )

        except ConsentRequiredError:
            raise  # surface the consent gate to the operator/router
        except Exception as exc:
            self._audit("code_reviewer.failed", detail={"error": str(exc)})
            return AgentResult(
                ok=False,
                output=f"Agent failed: {exc}",
                intent="code_reviewer",
                error=str(exc),
            )
