"""Auto-generated agent: coder.

search for the best free cloud coding agent in ollama and assign it to a sub agent called coder

Generated by the Agent Factory on 2026-08-12.
Task: search for the best free cloud coding agent in ollama and assign it to a sub agent called coder
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from agents.base import AgentResult, BaseAgent
from security.guardian import ConsentRequiredError

if TYPE_CHECKING:
    from agents.router import Pipeline


class Coder(BaseAgent):
    name = "coder"
    description = "search for the best free cloud coding agent in ollama and assign it to a sub agent called coder"

    # Assigned Ollama model — this agent's LLM calls use it directly
    # (None = the normal router path: cloud gemma4 primary / local fallback).
    ollama_model = 'qwen3-coder-next'

    # Tool allowlist — least-privilege scoping.
    tool_allowlist = frozenset({"fetch_page", "list_dir", "ollama_registry_search", "read_file", "web_search"})

    def __init__(self, pipeline: "Pipeline") -> None:
        super().__init__(pipeline)

    async def run(self, request: str) -> AgentResult:
        """Execute the agent's task."""
        self._audit("coder.started", detail={"request": request[:200]})

        try:
            outputs = []
            actions = []

                        # Search the web for relevant information.
            search_output = await self.pipeline.control.execute(
                "web_search", actor=self.name, query=request, n=5
            )
            outputs.append(f"Search results: {search_output[:500]}")
            actions.append({"tool": "web_search", "args": {"query": request}})

            # Fetch and read relevant pages.
            # (In a full implementation, parse search results for URLs first.)
            pass  # Pages fetched on demand via search results.

            # Synthesize the final answer with THIS agent's own Ollama model
            # (assigned at creation; falls back to the normal LLM path when
            # the model is unavailable or unset).  A model hiccup never fails
            # the turn — gathered outputs are still returned.
            try:
                answer = await self.pipeline.llm.complete(
                    [
                        {"role": "system", "content": "You are coder, a specialist agent. search for the best free cloud coding agent in ollama and assign it to a sub agent called coder"},
                        {"role": "user", "content": "Task: " + request + "\n\nFindings:\n" + ("\n\n".join(outputs) if outputs else "(none)")},
                    ],
                    temperature=0.6,
                    max_tokens=600,
                    model=self.ollama_model or None,
                )
                outputs.append(answer)
            except Exception:
                pass  # keep going with whatever the tools gathered

            self._audit("coder.completed", detail={"outputs": len(outputs)})

            return AgentResult(
                ok=True,
                output="\n\n".join(outputs) if outputs else "Task completed.",
                intent="coder",
                actions=actions,
            )

        except ConsentRequiredError:
            raise  # surface the consent gate to the operator/router
        except Exception as exc:
            self._audit("coder.failed", detail={"error": str(exc)})
            return AgentResult(
                ok=False,
                output=f"Agent failed: {exc}",
                intent="coder",
                error=str(exc),
            )
